add canned request saving and listing
fiberplane/fiberplane pull request #55
Opened 2024-06-26 13:18 UTC by mellowagain

2024-06-28 22:11 UTC, hatchan requested changes

2024-06-28 22:11 UTC, hatchan commented on fpx/src/api.rs
> +    fpx_directory: FpxDirectoryPath,
Maybe we should just wrap the base_url and fpx_directory in a "Config" Struct and wrap that in a Arc. Otherwise we will keep getting more of these wrapping types.

2024-06-28 22:11 UTC, hatchan commented on fpx/src/api/handlers/canned_requests.rs
> +) -> Result<StatusCode, ApiServerError<CannedRequestCreateError>> {
I'm not a fan of this pattern. I think we should just stick to the usual pattern where we accept a different payload, than what we return. Than we can move all the query string arguments to json body.

2024-06-28 22:11 UTC, hatchan commented on fpx/src/api/handlers/canned_requests.rs
> +    UnknownType,
`InvalidType` seems better here.

2024-06-28 22:11 UTC, hatchan commented on fpx/src/api/handlers/canned_requests.rs
> +    FileWriteFailed,
These seem like very vague errors to me. I think we can map these to simple InternalServerError's and just log it on the server side.

2024-06-28 22:11 UTC, hatchan commented on fpx/src/api/handlers/canned_requests.rs
> +    #[error("file not found")]
```suggestion
    #[error("canned request not found")]
```

2024-07-02 18:17 UTC, hatchan commented
I made some comments, but they ended up on the commit

2024-07-03 13:02 UTC, mellowagain commented
re-adding it seemed trickier than it did at first, it adds an implicit bound that the `Internal(anyhow::Error)` variant needed `serde::Deserialize` as well, despite being marked with `#[serde(skip, default)]`. I worked around this by making a newtype which implements these two traits

2024-07-10 09:17 UTC, hatchan commented on fpx/src/api/handlers/canned_requests.rs
> +    Internal(
I don't think we should have an `Internal` variant, given that we already have the CommonErrors Internal error. 

Regarding the easy propagation using the `?` operator, I think we should investigate where we are returning these anyhow errors and either refactor them to a typed error or just do a `map_error`

I think we might be able to create a `From` for anyhow Error into a `ApiServerError<E>`, which should always result in a Common error. I will investigate this shortly.

2024-07-25 12:30 UTC, hatchan approved these changes

2024-07-29 09:12 UTC, mellowagain commented on fpx/Cargo.toml
> +libsql = { version = "0.4", default-features = false, features = ["core", "serde", "replication"] }
adding this feature is required to make `libql` compile under windows

2024-07-29 13:26 UTC, merged